# Generated by Django 5.0.7 on 2024-07-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_day_time', models.BooleanField()),
                ('temperatute', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('wind_speed', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('wind_direction', models.CharField(max_length=1)),
                ('precipitation_perc', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('humidity_perc', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('short_forecast', models.CharField(max_length=100)),
            ],
        ),
    ]
